---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - crd.yml
  - serviceaccount.yml
  - clusterrolebinding.yml
  - deployment.yml

images:
  - name: helm-controller
    newName: rancher/helm-controller
    newTag: "v0.16.18@sha256:de5eb9199ab1e8570064bfe14a9f727eaa91052bfcdfd10e71d12d5859f03c15"

...
